import type { ComponentType } from "react";
import {
  AllocationDonut,
  BeforeAfter,
  ChangeRadar,
  ChatMessage,
  Client360,
  ClientBook,
  ConflictsList,
  DnaCard,
  DnaRadar,
  DriftBars,
  EmailDraft,
  FitHeatmap,
  MeetingPrep,
  PortfolioView,
  RelationshipTimeline,
  Research,
  SectorTreemap,
  VoiceNoteWidget,
} from "../components/widgets";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const registry = new Map<string, ComponentType<any>>([
  ["AllocationDonut", AllocationDonut],
  ["BeforeAfter", BeforeAfter],
  ["ChangeRadar", ChangeRadar],
  ["ChatMessage", ChatMessage],
  ["Client360", Client360],
  ["ClientBook", ClientBook],
  ["ConflictsList", ConflictsList],
  ["PortfolioView", PortfolioView],
  ["DnaCard", DnaCard],
  ["DnaRadar", DnaRadar],
  ["DriftBars", DriftBars],
  ["EmailDraft", EmailDraft],
  ["FitHeatmap", FitHeatmap],
  ["MeetingPrep", MeetingPrep],
  ["RelationshipTimeline", RelationshipTimeline],
  ["Research", Research],
  ["SectorTreemap", SectorTreemap],
  ["VoiceNoteWidget", VoiceNoteWidget],
]);
